# Generated by Django 6.0.3 on 2026-04-15 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(blank=True, help_text='e.g., Fleet Manager, Senior Driver', max_length=100, null=True)),
                ('licence_number', models.CharField(max_length=50, unique=True)),
                ('licence_class', models.CharField(choices=[('LR', 'Light Rigid'), ('MR', 'Medium Rigid'), ('HR', 'Heavy Rigid'), ('HC', 'Heavy Combination'), ('MC', 'Multi Combination')], default='HR', max_length=2)),
                ('licence_expiry', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postcode', models.CharField(blank=True, max_length=10, null=True)),
                ('medical_expiry', models.DateField(blank=True, null=True)),
                ('has_medical_certificate', models.BooleanField(default=False)),
                ('induction_date', models.DateField(blank=True, null=True)),
                ('last_training_date', models.DateField(blank=True, null=True)),
                ('next_training_due', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('review_due', 'Review Due'), ('expired', 'Expired'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('licence_document', models.FileField(blank=True, null=True, upload_to='driver_licences/')),
                ('medical_document', models.FileField(blank=True, null=True, upload_to='driver_medical/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='sms_builder.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'drivers',
                'ordering': ['-created_at'],
            },
        ),
    ]
