# Generated by Django 6.0.3 on 2026-04-15 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0002_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('vin', models.CharField(help_text='17-character Vehicle Identification Number', max_length=17, unique=True)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(choices=[('rigid_lt_4_5t', 'Rigid Trucks (<4.5t)'), ('rigid_4_5_12t', 'Rigid Trucks (4.5t–12t)'), ('rigid_gt_12t', 'Rigid Trucks (>12t)'), ('b_doubles', 'B-Doubles'), ('tankers', 'Tankers'), ('tippers', 'Tippers'), ('road_trains', 'Road Trains'), ('flatbeds', 'Flatbeds'), ('prime_movers', 'Prime Movers'), ('refrigerated', 'Refrigerated Vehicles')], default='rigid_truck', max_length=20)),
                ('registration_expiry', models.DateField()),
                ('inspection_due_date', models.DateField(blank=True, null=True)),
                ('cof_expiry', models.DateField(blank=True, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100, null=True)),
                ('insurance_expiry', models.DateField(blank=True, null=True)),
                ('gross_vehicle_mass', models.DecimalField(blank=True, decimal_places=2, help_text='in kg', max_digits=10, null=True)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=2, help_text='in kg', max_digits=10, null=True)),
                ('load_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='in kg', max_digits=10, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('current', 'Current'), ('expired', 'Expired'), ('due_soon', 'Due Soon'), ('suspended', 'Suspended')], default='current', max_length=20)),
                ('rego_document', models.FileField(blank=True, null=True, upload_to='vehicle_rego/')),
                ('cof_document', models.FileField(blank=True, null=True, upload_to='vehicle_cof/')),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='vehicle_insurance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='sms_builder.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
