# Generated by Django 6.0.3 on 2026-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0003_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-file-earmark-text', 'Document'), ('bi-shield-check', 'Shield Check'), ('bi-truck', 'Truck'), ('bi-exclamation-triangle', 'Warning'), ('bi-bar-chart-line', 'Chart'), ('bi-person-lock', 'User Lock'), ('bi-building', 'Building'), ('bi-clock-history', 'History'), ('bi-graph-up', 'Graph'), ('bi-phone', 'Phone'), ('bi-envelope', 'Email'), ('bi-gear', 'Settings'), ('bi-star', 'Star'), ('bi-heart', 'Heart'), ('bi-cpu', 'CPU'), ('bi-cloud', 'Cloud'), ('bi-people', 'People'), ('bi-chat', 'Chat'), ('bi-calendar', 'Calendar'), ('bi-tools', 'Tools'), ('bi-headset', 'Support')], default='bi-truck', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
