# Generated by Django 6.0.3 on 2026-04-15 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_period', models.CharField(choices=[('month', 'Per Month'), ('year', 'Per Year'), ('one_time', 'One Time')], default='month', max_length=20)),
                ('features', models.JSONField(default=list, help_text='List of included features')),
                ('disabled_features', models.JSONField(default=list, help_text='List of disabled features')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('button_class', models.CharField(default='btn-outline-primary', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
                'db_table': 'pricing_plans',
                'ordering': ['order', 'price'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_plan',
            field=models.CharField(blank=True, default='starter', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='subscription_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('next_renewal_date', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('trial', 'Trial')], default='pending', max_length=20)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='sms_builder.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='sms_builder.pricingplan')),
            ],
            options={
                'verbose_name': 'Company Subscription',
                'verbose_name_plural': 'Company Subscriptions',
                'db_table': 'company_subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_changes', to=settings.AUTH_USER_MODEL)),
                ('new_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms_builder.pricingplan')),
                ('old_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='sms_builder.pricingplan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='sms_builder.companysubscription')),
            ],
            options={
                'verbose_name': 'Subscription History',
                'verbose_name_plural': 'Subscription Histories',
                'db_table': 'subscription_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
