# Generated by Django 6.0.3 on 2026-04-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0005_pricingplan_company_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Why PRODRIVE', help_text='Small text above title', max_length=100)),
                ('title', models.CharField(default='Built for the Road Ahead', max_length=200)),
                ('description', models.TextField(default='Our system is designed for usability, compliance support, and efficient document workflows.')),
                ('video_url', models.CharField(default='Cm6eMeOg-KU', help_text='YouTube video ID', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Why Us Section',
                'verbose_name_plural': 'Why Us Sections',
                'db_table': 'why_us',
            },
        ),
        migrations.CreateModel(
            name='WhyUsFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='bi-check-circle-fill', max_length=50)),
                ('text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('why_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sms_builder.whyus')),
            ],
            options={
                'verbose_name': 'Why Us Feature',
                'verbose_name_plural': 'Why Us Features',
                'db_table': 'why_us_features',
                'ordering': ['order'],
            },
        ),
    ]
