# Generated by Django 6.0.3 on 2026-04-15 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0007_contactmessage_footersettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(default='Web-Based Compliance Platform', max_length=255)),
                ('hero_title', models.CharField(default='Smarter Safety Management for Heavy Vehicle Operations', max_length=500)),
                ('hero_description', models.TextField(default='Build, manage, and monitor Safety Management System documents with a professional, responsive, and user-friendly web platform.')),
                ('hero_button_text', models.CharField(default='Get Started Free', max_length=100)),
                ('hero_button_link', models.CharField(default='../../form.html', max_length=255)),
                ('hero_video_url', models.CharField(default='https://www.youtube.com/embed/Cm6eMeOg-KU', max_length=255)),
                ('trust_item_1', models.CharField(default='No credit card required', max_length=255)),
                ('trust_item_2', models.CharField(default='NHVR aligned', max_length=255)),
                ('trust_item_3', models.CharField(default='Setup in 15 minutes', max_length=255)),
                ('carousel_images', models.JSONField(default=list, help_text='List of image URLs for carousel')),
                ('site_name', models.CharField(default='PRODRIVE', max_length=255)),
                ('site_tagline', models.CharField(default='SMS Builder', max_length=255)),
                ('version', models.CharField(default='v2.4.1', max_length=50)),
                ('environment', models.CharField(default='Production', max_length=20)),
                ('email_notifications', models.BooleanField(default=True)),
                ('new_registration_alerts', models.BooleanField(default=True)),
                ('incident_notifications', models.BooleanField(default=True)),
                ('compliance_reminders', models.BooleanField(default=True)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('last_backup', models.DateTimeField(blank=True, null=True)),
                ('database_status', models.CharField(default='Healthy', max_length=50)),
                ('uptime', models.CharField(default='99.97%', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_settings',
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='Super Administrator', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_profiles',
            },
        ),
    ]
