# Generated by Django 6.0.3 on 2026-04-16 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0008_systemsettings_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='declaration_accepted',
            field=models.BooleanField(default=False, help_text='User declared info is accurate'),
        ),
        migrations.AddField(
            model_name='company',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('rigid_lt_4_5t', 'Rigid Trucks (<4.5t)'), ('rigid_4_5_12t', 'Rigid Trucks (4.5t–12t)'), ('rigid_gt_12t', 'Rigid Trucks (>12t)'), ('b_doubles', 'B-Doubles'), ('tankers', 'Tankers'), ('tippers', 'Tippers'), ('road_trains', 'Road Trains'), ('flatbeds', 'Flatbeds'), ('prime_movers', 'Prime Movers'), ('refrigerated', 'Refrigerated Vehicles')], default='rigid_lt_4_5t', max_length=20),
        ),
        migrations.CreateModel(
            name='CompanyFleet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_vehicles', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('max_gvm', models.CharField(blank=True, max_length=50, null=True)),
                ('average_vehicle_age', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_types', models.JSONField(blank=True, default=list)),
                ('special_cargo', models.JSONField(blank=True, default=list)),
                ('nhvr_configurations', models.JSONField(blank=True, default=dict)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fleet', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Company Fleet',
                'verbose_name_plural': 'Company Fleets',
                'db_table': 'company_fleets',
            },
        ),
        migrations.CreateModel(
            name='CompanyIncidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_process', models.JSONField(blank=True, default=list)),
                ('incidents_last_12_months', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('incidents_last_3_years', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('injuries_resulting', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('improvement_actions', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident_profile', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Incident Profile',
                'verbose_name_plural': 'Incident Profiles',
                'db_table': 'company_incident_profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanyOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_types', models.JSONField(blank=True, default=list)),
                ('accreditations', models.JSONField(blank=True, default=list)),
                ('audit_date_none', models.DateField(blank=True, null=True)),
                ('audit_date_trucksafe', models.DateField(blank=True, null=True)),
                ('audit_date_wahva', models.DateField(blank=True, null=True)),
                ('operating_areas', models.JSONField(blank=True, default=list)),
                ('operating_hours', models.CharField(blank=True, max_length=50, null=True)),
                ('num_drivers', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Company Operation',
                'verbose_name_plural': 'Company Operations',
                'db_table': 'company_operations',
            },
        ),
        migrations.CreateModel(
            name='CompanyRiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_policies', models.JSONField(blank=True, default=list)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Company Risk Profile',
                'verbose_name_plural': 'Company Risk Profiles',
                'db_table': 'company_risk_profiles',
            },
        ),
        migrations.CreateModel(
            name='CompanySubcontractorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engages_subcontractors', models.BooleanField(default=False)),
                ('compliance_practices', models.JSONField(blank=True, default=list)),
                ('active_subcontractors', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('primary_engagement_type', models.CharField(blank=True, max_length=100, null=True)),
                ('review_frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('cor_procedures', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_profile', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Subcontractor Profile',
                'verbose_name_plural': 'Subcontractor Profiles',
                'db_table': 'company_subcontractor_profiles',
            },
        ),
        migrations.CreateModel(
            name='IncidentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('incident_type', models.CharField(blank=True, choices=[('Accident', 'Accident'), ('Near-Miss', 'Near-Miss'), ('Injury', 'Injury'), ('Property Damage', 'Property Damage'), ('Dangerous Goods', 'Dangerous Goods')], max_length=50, null=True)),
                ('outcome', models.CharField(blank=True, max_length=255, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_records', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Incident Record',
                'verbose_name_plural': 'Incident Records',
                'db_table': 'company_incident_records',
                'ordering': ['-incident_date'],
            },
        ),
        migrations.CreateModel(
            name='RiskHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard_description', models.CharField(max_length=255)),
                ('likelihood', models.CharField(choices=[('Rare', 'Rare'), ('Unlikely', 'Unlikely'), ('Possible', 'Possible'), ('Likely', 'Likely'), ('Almost Certain', 'Almost Certain')], max_length=20)),
                ('consequence', models.CharField(choices=[('Insignificant', 'Insignificant'), ('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major'), ('Catastrophic', 'Catastrophic')], max_length=20)),
                ('control_measures', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_hazards', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Risk Hazard',
                'verbose_name_plural': 'Risk Hazards',
                'db_table': 'company_risk_hazards',
            },
        ),
        migrations.CreateModel(
            name='SubcontractorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcontractor_name', models.CharField(max_length=255)),
                ('abn', models.CharField(blank=True, max_length=20, null=True)),
                ('licence_type', models.CharField(blank=True, max_length=100, null=True)),
                ('contract_expiry', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractor_records', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Subcontractor Record',
                'verbose_name_plural': 'Subcontractor Records',
                'db_table': 'company_subcontractor_records',
            },
        ),
    ]
