# Generated by Django 6.0.3 on 2026-04-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0011_driver_approval_status_driver_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('change_requested', 'Change Requested'), ('change_approved', 'Change Approved'), ('change_rejected', 'Change Rejected'), ('change_cancelled', 'Change Cancelled')], max_length=50),
        ),
    ]
