# Generated by Django 6.0.3 on 2026-04-27 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0013_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_document',
            field=models.FileField(blank=True, help_text='Upload a related company document (PDF only)', null=True, upload_to='company_docs/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
