# Generated by Django 6.0.3 on 2026-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0015_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='doc_type',
            field=models.CharField(blank=True, choices=[('FULL_DOC', 'Full Document'), ('RISK_DOC', 'Risk Document'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
