# Generated by Django 6.0.3 on 2026-04-29 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_builder', '0016_companydocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stripe_default_payment_method_id',
            field=models.CharField(blank=True, help_text='Default payment method', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='last_payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='last_payment_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='last_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Payment Intent ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='stripe_setup_intent_id',
            field=models.CharField(blank=True, help_text='Stripe Setup Intent ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, help_text='Stripe Subscription ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='trial_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companysubscription',
            name='trial_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='stripe_lookup_key',
            field=models.CharField(blank=True, help_text='Stripe lookup key for this plan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for this plan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe Product ID for this plan', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='stripe_event_id',
            field=models.CharField(blank=True, help_text='Stripe Event ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionhistory',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, help_text='Stripe Invoice ID', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companysubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('pending', 'Pending'), ('trial', 'Trial'), ('past_due', 'Past Due'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('unpaid', 'Unpaid')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('upgraded', 'Upgraded'), ('downgraded', 'Downgraded'), ('renewed', 'Renewed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('change_requested', 'Change Requested'), ('change_approved', 'Change Approved'), ('change_rejected', 'Change Rejected'), ('change_cancelled', 'Change Cancelled'), ('payment_succeeded', 'Payment Succeeded'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('invoice_paid', 'Invoice Paid'), ('invoice_payment_failed', 'Invoice Payment Failed'), ('subscription_updated', 'Subscription Updated'), ('subscription_deleted', 'Subscription Deleted'), ('trial_started', 'Trial Started'), ('trial_ended', 'Trial Ended'), ('past_due', 'Past Due')], max_length=50),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=100, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('card', 'Card'), ('bank_account', 'Bank Account')], default='card', max_length=20)),
                ('is_default', models.BooleanField(default=False)),
                ('card_brand', models.CharField(blank=True, choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express'), ('discover', 'Discover'), ('jcb', 'JCB'), ('diners', 'Diners Club'), ('unionpay', 'UnionPay'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('card_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('cardholder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_last4', models.CharField(blank=True, max_length=4, null=True)),
                ('bank_account_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='sms_builder.company')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Stripe Event ID', max_length=100, unique=True)),
                ('event_type', models.CharField(choices=[('customer.subscription.created', 'Subscription Created'), ('customer.subscription.updated', 'Subscription Updated'), ('customer.subscription.deleted', 'Subscription Deleted'), ('invoice.paid', 'Invoice Paid'), ('invoice.payment_failed', 'Invoice Payment Failed'), ('payment_intent.succeeded', 'Payment Succeeded'), ('payment_intent.payment_failed', 'Payment Failed'), ('checkout.session.completed', 'Checkout Session Completed'), ('customer.updated', 'Customer Updated'), ('customer.deleted', 'Customer Deleted')], max_length=100)),
                ('api_version', models.CharField(blank=True, max_length=50, null=True)),
                ('data', models.JSONField(help_text='Full event data from Stripe')),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_id'], name='stripe_webh_event_i_6b18cc_idx'), models.Index(fields=['event_type'], name='stripe_webh_event_t_2d6957_idx'), models.Index(fields=['processed'], name='stripe_webh_process_f53e30_idx')],
            },
        ),
    ]
